#! /bin/bash

if type cygpath > /dev/null 2>&1; then
    THISDIR="$(cygpath -w -a .)"
    PATHSEP=";"
else
    THISDIR="$(pwd)"
    PATHSEP=":"
fi

if test -z "$PYTHON"; then
    PYTHON=python
fi

if test -z "$PYTHONPATH"; then
    PYTHONPATH="$THISDIR"
fi

PYTHONPATH="$PYTHONPATH$PATHSEP$THISDIR/lib"

export PYTHONPATH

$PYTHON main.py $ARGS "$@"
